### ISSUE TITLE
[bug] Layout 2 columns

### ISSUE THREAD

**Issue by oscarmcm** [aziz/DistractionFreeWindow#6] opened 2016-05-31 22:04 UTC
- **Sublime Text Version**: 
    - 3
- **Build**:
    - 3114
- **Steps**:
    - Select two columns layout => View > Layout > Columns 2
    - Set active cursor in pane 1.
    - Activate the plugin.
    - Change to pane 2.
    - Deactivate the plugin.
    - Plugin has no effect.

**Comment by jrappen** [comment] 2016-07-02 13:36
Caused by:

* [distraction_free_window.py#L28](https://github.com/aziz/DistractionFreeWindow/blob/24071a0d35cc21f682ff66de37f5c3382dfbe788/distraction_free_window.py#L28)
* [distraction_free_window.py#L30](https://github.com/aziz/DistractionFreeWindow/blob/24071a0d35cc21f682ff66de37f5c3382dfbe788/distraction_free_window.py#L30)
* [distraction_free_window.py#L172-L174](https://github.com/aziz/DistractionFreeWindow/blob/24071a0d35cc21f682ff66de37f5c3382dfbe788/distraction_free_window.py#L172-L174)

**Comment by jrappen** [comment] 2016-07-09 21:04
This issue could be fixed if settings for the view were not saved to cached settings, but the `Settings - User` file for **DistractionFreeWindow**. Proposing something like a dictionary `toggledViews`, with `id` (key of view) / `isEnabled` (value) pairs. Haven't checked the API, but this should be possible. Not sure if settings should be flushed when rebooting Sublime.

Thinking loud here, any remarks / ideas?

/cc @oscarmcm @aziz

**Comment by jrappen** [comment] 2016-08-19 20:41
@oscarmcm please confirm the changes to the `develop` branch fix this issue.

**Comment by oscarmcm** [comment] 2016-08-20 20:59
@jrappen the problem still continues, although it has released a new version of the package?

**Comment by jrappen** [comment] 2016-08-21 17:05
@oscarmcm I bumped to `0.5.1` just now, please re-open this issue if problems persist.

**Comment by jrappen** [comment] 2016-08-22 17:39
Will need to review this issue. My fix broke ST2 in `0.5.1` and I reverted changes in `0.5.2`.

**Comment by jrappen** [comment] 2016-09-08 14:49
@oscarmcm Your issue has finally been fixed in `0.6`. I have tested the changes with the latest builds of ST2 and ST3.

Package Control has been offline for nearly a week now (see wbond/package_control#1143), so it may take a while for Package Control to update your packages, should you be using that.

Please reopen this issue should problems persist.

**Comment by jrappen** [comment] 2016-09-10 17:44
Package Control is back up and should be updating DistractionFreeWindow to `0.6.1` shortly. I'd appreciate a note here whether or not `0.6.1` fixes your issue described above.

**Comment by oscarmcm** [comment] 2016-09-12 21:04
@jrappen I just try the latest release and the keyboard shortcut does not execute the command

Default (OSX).sublime-keymap - User
`[
	{ "keys": ["super+shift+f11"], "command": "distraction_free_window" }
]
`

**Comment by jrappen** [comment] 2016-09-13 07:12
@oscarmcm

I cannot reproduce this as I'm not on OSX, changing the default keyboard shortcut to something else on Windows works as expected.

Could you check the console when trying your shortcut after having enabled `import sublime; sublime.log_commands(True)` there?

**Comment by oscarmcm** [comment] 2016-09-17 19:08
Hey @jrappen there is the stack trace

```python
Traceback (most recent call last):
  File "/Applications/Sublime Text.app/Contents/MacOS/sublime_plugin.py", line 553, in run_
    return self.run()
  File "distraction_free_window in /Users/foo/Library/Application Support/Sublime Text 3/Installed Packages/DistractionFreeWindow.sublime-package", line 29, in run
  File "distraction_free_window in /Users/foo/Library/Application Support/Sublime Text 3/Installed Packages/DistractionFreeWindow.sublime-package", line 192, in is_menu_visible
AttributeError: 'Window' object has no attribute 'is_menu_visible'
```

**Comment by jrappen** [comment] 2016-09-18 09:07
@oscarmcm that helps, thanks. Will fix right away!

**Closed** 2016-09-18 09:23 UTC
Labels: bug
